name: Build with publish

on:
  workflow_call:

jobs:
  build_with_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          if ./gradlew tasks | grep -wq ^lintKotlin; then
            ./gradlew build -x lintKotlin
          else
            ./gradlew build
          fi

      - name: Publish
        if: github.ref_name == 'main'
        run: ./gradlew publish

      - name: Determine snapshot props
        if: startsWith(github.ref_name, 'dev/')
        id: snapshot-props
        run: |
          props=$(./gradlew properties --quiet)

          group=$(echo "$props" | grep '^group:' | cut -d ' ' -f 2)
          name=$(echo "$props" | grep '^name:' | cut -d ' ' -f 2)
          packageName=$group.$name
          echo "package-name=$packageName" >> $GITHUB_OUTPUT
          echo Package name: $packageName

          version=$(echo "$props" | grep '^version:' | cut -d ' ' -f 2)
          if [[ ! "$version" =~ -SNAPSHOT$ ]]; then
            version="$version-SNAPSHOT"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          echo Snapshot version: $version

      - name: Delete old snapshot
        uses: actions/delete-package-versions@v5
        if: steps.snapshot-props.outcome == 'success'
        with:
          package-type: maven
          package-name: ${{ steps.snapshot-props.outputs.package-name }}
          num-old-versions-to-delete: 1
          # Matcher alt unntatt bestemt snapshot-versjon
          ignore-versions: ^(?!${{ steps.snapshot-props.outputs.version }}$).*

      - name: Publish snapshot
        if: steps.snapshot-props.outcome == 'success'
        run: ./gradlew publish -Pversion=${{ steps.snapshot-props.outputs.version }}
