name: Dependency submission

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: 21

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v6
        with:
          cache-provider: basic
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
